// AUTO-GENERATED by script/photos.ts — do not edit by hand.
// Run `npm run photos` to regenerate after changing client/public/photos/_src/.

export interface PhotoVariant {
  width: number;
  webp: string;
  jpg: string;
}

export interface Photo {
  /** Base name without extension, e.g. "hero-1". */
  name: string;
  /** Intrinsic (EXIF-oriented) pixel dimensions of the source. */
  width: number;
  height: number;
  /** width / height, rounded to 4 dp. */
  aspectRatio: number;
  /** Tiny blurred JPG as a data URI, for blur-up placeholders. */
  lqip: string;
  /** Emitted sizes, ascending by width. */
  variants: PhotoVariant[];
  /** Largest JPG URL — use as a plain <img src> fallback. */
  src: string;
  /** JPG srcset string for <img srcset> / <source>. */
  srcSet: string;
  /** WebP srcset string for a <source type="image/webp">. */
  webpSrcSet: string;
}

export const photos: Photo[] = [
  {
    "name": "hero-1",
    "width": 5184,
    "height": 3456,
    "aspectRatio": 1.5,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAEDBP/EACAQAAIBBQACAwAAAAAAAAAAAAECAAMEESExEkETIiP/xAAWAQEBAQAAAAAAAAAAAAAAAAABAgT/xAAZEQACAwEAAAAAAAAAAAAAAAAAAQIRIUH/2gAMAwEAAhEDEQA/AJfEyr+ewexULZ1r/YaPI7WujkqhzL12FEebEtrWPUzxt4xVdMF8zW7EHBB5CY7uu1wck89QlxWaB//Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-1-640.webp",
        "jpg": "/photos/hero-1-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-1-960.webp",
        "jpg": "/photos/hero-1-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-1-1440.webp",
        "jpg": "/photos/hero-1-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-1-1920.webp",
        "jpg": "/photos/hero-1-1920.jpg"
      }
    ],
    "src": "/photos/hero-1-1920.jpg",
    "srcSet": "/photos/hero-1-640.jpg 640w, /photos/hero-1-960.jpg 960w, /photos/hero-1-1440.jpg 1440w, /photos/hero-1-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-1-640.webp 640w, /photos/hero-1-960.webp 960w, /photos/hero-1-1440.webp 1440w, /photos/hero-1-1920.webp 1920w"
  },
  {
    "name": "hero-2",
    "width": 5760,
    "height": 3840,
    "aspectRatio": 1.5,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABgDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAwAEBv/EAB4QAAIBBAMBAAAAAAAAAAAAAAECAwAFERIEEyFB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQL/xAAWEQEBAQAAAAAAAAAAAAAAAAAAARH/2gAMAwEAAhEDEQA/AOfa3SGPtjQtH9Iop7fLCivqdCM5prZdZOI+jnaFvCDT3NppeOWWXaEnKrU24qRimjCxrj2qgMjdYGfKqRr/2Q==",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-2-640.webp",
        "jpg": "/photos/hero-2-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-2-960.webp",
        "jpg": "/photos/hero-2-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-2-1440.webp",
        "jpg": "/photos/hero-2-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-2-1920.webp",
        "jpg": "/photos/hero-2-1920.jpg"
      }
    ],
    "src": "/photos/hero-2-1920.jpg",
    "srcSet": "/photos/hero-2-640.jpg 640w, /photos/hero-2-960.jpg 960w, /photos/hero-2-1440.jpg 1440w, /photos/hero-2-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-2-640.webp 640w, /photos/hero-2-960.webp 960w, /photos/hero-2-1440.webp 1440w, /photos/hero-2-1920.webp 1920w"
  },
  {
    "name": "hero-3",
    "width": 3506,
    "height": 5260,
    "aspectRatio": 0.6665,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGQABAQADAQAAAAAAAAAAAAAAAAUCBAYD/8QAJBAAAgIBBAIBBQAAAAAAAAAAAQIAAyEEBRESMUEGEyIjJFH/xAAYAQADAQEAAAAAAAAAAAAAAAAAAgMBBP/EABkRAAMBAQEAAAAAAAAAAAAAAAABAhExIf/aAAwDAQACEQMRAD8A4/kCZVqbG6rkxQodup9yztNKrr6wEBx7iVWDzOklqGVuvGf5Et71Sn12eoZ98RMVajXOMkW9KXJC8HmZU6569QLVHj1PR6e9jqfPGJpEFWIPkQWMG2i7t1r61nVRzbZg8+AIlH4tpxVpGvcZY4iSp4/Ci1ohIf2WmlqR+doiUnolcO520ddsoAx9sRE566VXD//Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-3-640.webp",
        "jpg": "/photos/hero-3-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-3-960.webp",
        "jpg": "/photos/hero-3-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-3-1440.webp",
        "jpg": "/photos/hero-3-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-3-1920.webp",
        "jpg": "/photos/hero-3-1920.jpg"
      }
    ],
    "src": "/photos/hero-3-1920.jpg",
    "srcSet": "/photos/hero-3-640.jpg 640w, /photos/hero-3-960.jpg 960w, /photos/hero-3-1440.jpg 1440w, /photos/hero-3-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-3-640.webp 640w, /photos/hero-3-960.webp 960w, /photos/hero-3-1440.webp 1440w, /photos/hero-3-1920.webp 1920w"
  },
  {
    "name": "hero-4",
    "width": 2333,
    "height": 3500,
    "aspectRatio": 0.6666,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAUCAwYE/8QAIxAAAgIBAwQDAQAAAAAAAAAAAQIAAxEEEiEFE1FxIzE0Qf/EABcBAAMBAAAAAAAAAAAAAAAAAAACAwH/xAAZEQEBAQEBAQAAAAAAAAAAAAAAAQISAzH/2gAMAwEAAhEDEQA/AMu6BMeTIrYd2MlY0fp1rvuZCFxOW7RBRnPPiT7inF+qS71thLcwlOO2/qE0pzX1zUam1aSFVCZC+wDUMu3n+Rbo/wBSe5oHpQuLSOQImpJT41WevD9wlkIhHNqo+d2DCE2Lgp04xrQB9Zj+w/GIQh6Mw5SOYQhJKv/Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-4-640.webp",
        "jpg": "/photos/hero-4-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-4-960.webp",
        "jpg": "/photos/hero-4-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-4-1440.webp",
        "jpg": "/photos/hero-4-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-4-1920.webp",
        "jpg": "/photos/hero-4-1920.jpg"
      }
    ],
    "src": "/photos/hero-4-1920.jpg",
    "srcSet": "/photos/hero-4-640.jpg 640w, /photos/hero-4-960.jpg 960w, /photos/hero-4-1440.jpg 1440w, /photos/hero-4-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-4-640.webp 640w, /photos/hero-4-960.webp 960w, /photos/hero-4-1440.webp 1440w, /photos/hero-4-1920.webp 1920w"
  },
  {
    "name": "hero-5",
    "width": 2086,
    "height": 3129,
    "aspectRatio": 0.6667,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGQABAAMBAQAAAAAAAAAAAAAAAAMEBQIG/8QAJRAAAgEDBAEEAwAAAAAAAAAAAAECAwQREhMhQTEUIjM0UWFi/8QAFwEAAwEAAAAAAAAAAAAAAAAAAAECA//EABgRAQEBAQEAAAAAAAAAAAAAAAABMQJR/9oADAMBAAIRAxEAPwDAjSlHiaw+mUrj5Gb17RzjbeUzFr21SL1S7ZMq7z4rN48A6qQcXysApL1Vu1tJNpsz6kF6yTlzH8E9rcpRa0e4qXLnRnuLmLfZnGlqavbwrx040/sHEa27pXgFFqaUVGqsdkN99Fv+gBTSqjbVJRy0/AAAP//Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-5-640.webp",
        "jpg": "/photos/hero-5-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-5-960.webp",
        "jpg": "/photos/hero-5-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-5-1440.webp",
        "jpg": "/photos/hero-5-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-5-1920.webp",
        "jpg": "/photos/hero-5-1920.jpg"
      }
    ],
    "src": "/photos/hero-5-1920.jpg",
    "srcSet": "/photos/hero-5-640.jpg 640w, /photos/hero-5-960.jpg 960w, /photos/hero-5-1440.jpg 1440w, /photos/hero-5-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-5-640.webp 640w, /photos/hero-5-960.webp 960w, /photos/hero-5-1440.webp 1440w, /photos/hero-5-1920.webp 1920w"
  },
  {
    "name": "hero-6",
    "width": 6000,
    "height": 4000,
    "aspectRatio": 1.5,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABgDASIAAhEBAxEB/8QAGAAAAgMAAAAAAAAAAAAAAAAAAAQCAwX/xAAfEAABBAEFAQAAAAAAAAAAAAABAAIDBBEFBiEiMRL/xAAVAQEBAAAAAAAAAAAAAAAAAAABAP/EABURAQEAAAAAAAAAAAAAAAAAAAAB/9oADAMBAAIRAxEAPwBbRYYrEDy8ZOVM1IxaiDepa5Vbfx8Scpa7ZdXvlw7Fp8KAc3BIGwtYB6ULIt6hJbAEmMA8ITVH/9k=",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-6-640.webp",
        "jpg": "/photos/hero-6-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-6-960.webp",
        "jpg": "/photos/hero-6-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-6-1440.webp",
        "jpg": "/photos/hero-6-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-6-1920.webp",
        "jpg": "/photos/hero-6-1920.jpg"
      }
    ],
    "src": "/photos/hero-6-1920.jpg",
    "srcSet": "/photos/hero-6-640.jpg 640w, /photos/hero-6-960.jpg 960w, /photos/hero-6-1440.jpg 1440w, /photos/hero-6-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-6-640.webp 640w, /photos/hero-6-960.webp 960w, /photos/hero-6-1440.webp 1440w, /photos/hero-6-1920.webp 1920w"
  },
  {
    "name": "hero-7",
    "width": 6000,
    "height": 4000,
    "aspectRatio": 1.5,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAABQAE/8QAHxAAAgICAgMBAAAAAAAAAAAAAQIABAMRBUEhIlJh/8QAFgEBAQEAAAAAAAAAAAAAAAAAAwAB/8QAFhEBAQEAAAAAAAAAAAAAAAAAAQAR/9oADAMBAAIRAxEAPwAjjq2TOjjGda7iGKowQjRLCHVOTNIKqID9fsaqXUtAsngnqZlDYs/G49bZdEym24rr772JQVRlAS//2Q==",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-7-640.webp",
        "jpg": "/photos/hero-7-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-7-960.webp",
        "jpg": "/photos/hero-7-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-7-1440.webp",
        "jpg": "/photos/hero-7-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-7-1920.webp",
        "jpg": "/photos/hero-7-1920.jpg"
      }
    ],
    "src": "/photos/hero-7-1920.jpg",
    "srcSet": "/photos/hero-7-640.jpg 640w, /photos/hero-7-960.jpg 960w, /photos/hero-7-1440.jpg 1440w, /photos/hero-7-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-7-640.webp 640w, /photos/hero-7-960.webp 960w, /photos/hero-7-1440.webp 1440w, /photos/hero-7-1920.webp 1920w"
  },
  {
    "name": "hero-8",
    "width": 2333,
    "height": 3500,
    "aspectRatio": 0.6666,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGgAAAgMBAQAAAAAAAAAAAAAAAAQDBQYBAv/EACMQAAICAgEDBQEAAAAAAAAAAAECAAMEERITMUEFISJxgTL/xAAXAQEBAQEAAAAAAAAAAAAAAAABAAIE/8QAGxEBAQEAAgMAAAAAAAAAAAAAAAERAjEDIVH/2gAMAwEAAhEDEQA/APBx2UDkPySrjOEJHtrsZoB6ZWNmw8jEeOIl7UlyNDez2nLPHZTjO5a8wX19wjPrVNQ10W/o/IQjJ9WLC7LzumTz39SvsuY47chp9+5MmTKuTaldzl6DIrIHmaxueidurVVwe4hJFq6OM9ZXZ8EwheMGGqmPS8RLIyLKWYVkD8hCM6V7V9mRa4PJzCEIl//Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-8-640.webp",
        "jpg": "/photos/hero-8-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-8-960.webp",
        "jpg": "/photos/hero-8-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-8-1440.webp",
        "jpg": "/photos/hero-8-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-8-1920.webp",
        "jpg": "/photos/hero-8-1920.jpg"
      }
    ],
    "src": "/photos/hero-8-1920.jpg",
    "srcSet": "/photos/hero-8-640.jpg 640w, /photos/hero-8-960.jpg 960w, /photos/hero-8-1440.jpg 1440w, /photos/hero-8-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-8-640.webp 640w, /photos/hero-8-960.webp 960w, /photos/hero-8-1440.webp 1440w, /photos/hero-8-1920.webp 1920w"
  },
  {
    "name": "hero-9",
    "width": 3375,
    "height": 6000,
    "aspectRatio": 0.5625,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAArABgDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAEFBAP/xAAkEAACAgEEAgEFAAAAAAAAAAABAgADBBESITEFQRMUIjNSkf/EABcBAAMBAAAAAAAAAAAAAAAAAAABAgP/xAAaEQEBAAIDAAAAAAAAAAAAAAABABFRAiFh/9oADAMBAAIRAxEAPwCfmXtl2G2zmT2Uv0CI1tJJU9nqPSywhBxx/Zj3aqWaxXHfMIrWdWKngiEooavlVrSu74iGA010mvxOJj3JWL3G8j7dPUPqRa7WAh6+tpE61nHx7EsaraewRA9rxq0eS8XjU4jBVDW/sYRZ2ZTm1BEs+M+9YQXUzhugYuQKWtXTVewJox8z56Xrs77EnU/kjo4ySB1CidblMhkZjt9QjIBzBqPUIYmKX//Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-9-640.webp",
        "jpg": "/photos/hero-9-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-9-960.webp",
        "jpg": "/photos/hero-9-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-9-1440.webp",
        "jpg": "/photos/hero-9-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-9-1920.webp",
        "jpg": "/photos/hero-9-1920.jpg"
      }
    ],
    "src": "/photos/hero-9-1920.jpg",
    "srcSet": "/photos/hero-9-640.jpg 640w, /photos/hero-9-960.jpg 960w, /photos/hero-9-1440.jpg 1440w, /photos/hero-9-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-9-640.webp 640w, /photos/hero-9-960.webp 960w, /photos/hero-9-1440.webp 1440w, /photos/hero-9-1920.webp 1920w"
  },
  {
    "name": "hero-10",
    "width": 4000,
    "height": 6000,
    "aspectRatio": 0.6667,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGQABAQADAQAAAAAAAAAAAAAAAAIBAwQF/8QAIhAAAgIBAwQDAAAAAAAAAAAAAAECAxESMTIEEyFxBSJB/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/APNl8v1t+YyteGaqW1YpavvHzk43N/nhFRscXlbgV1E3ZbKcuTfkEyfcTb3AGsFPCTT3MR5L2B1U0Q7Wqc9ILrvjVc4yWYSAHHPkzEdwALu5L0AAP//Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-10-640.webp",
        "jpg": "/photos/hero-10-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-10-960.webp",
        "jpg": "/photos/hero-10-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-10-1440.webp",
        "jpg": "/photos/hero-10-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-10-1920.webp",
        "jpg": "/photos/hero-10-1920.jpg"
      }
    ],
    "src": "/photos/hero-10-1920.jpg",
    "srcSet": "/photos/hero-10-640.jpg 640w, /photos/hero-10-960.jpg 960w, /photos/hero-10-1440.jpg 1440w, /photos/hero-10-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-10-640.webp 640w, /photos/hero-10-960.webp 960w, /photos/hero-10-1440.webp 1440w, /photos/hero-10-1920.webp 1920w"
  },
  {
    "name": "hero-11",
    "width": 4480,
    "height": 6720,
    "aspectRatio": 0.6667,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGQABAQEBAQEAAAAAAAAAAAAAAAMFBAIG/8QAIBAAAQQBBQEBAAAAAAAAAAAAAQACAwQRBRITITFBUf/EABYBAQEBAAAAAAAAAAAAAAAAAAACAf/EABkRAAIDAQAAAAAAAAAAAAAAAAABAhExIf/aAAwDAQACEQMRAD8A+jiY1gwAArAgD1Z0lxkQG54bnxQu6oys1me3POAEoWbBmaEWBJqz22mx8RLcZyiw0lqFcvj3kjoffixXjmlbyyF20dELasZsVdvJ6MYXDUoGIkPIOUq2L4TdciiaOy9zUVLdfij3tjz+lFrk48CimNMkdJAS457XU848RFccJenu04moQfxERRPSo4f/2Q==",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-11-640.webp",
        "jpg": "/photos/hero-11-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-11-960.webp",
        "jpg": "/photos/hero-11-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-11-1440.webp",
        "jpg": "/photos/hero-11-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-11-1920.webp",
        "jpg": "/photos/hero-11-1920.jpg"
      }
    ],
    "src": "/photos/hero-11-1920.jpg",
    "srcSet": "/photos/hero-11-640.jpg 640w, /photos/hero-11-960.jpg 960w, /photos/hero-11-1440.jpg 1440w, /photos/hero-11-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-11-640.webp 640w, /photos/hero-11-960.webp 960w, /photos/hero-11-1440.webp 1440w, /photos/hero-11-1920.webp 1920w"
  },
  {
    "name": "hero-12",
    "width": 2425,
    "height": 3799,
    "aspectRatio": 0.6383,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAmABgDASIAAhEBAxEB/8QAGQABAAMBAQAAAAAAAAAAAAAAAAMEBgUH/8QAIhAAAgICAQUAAwAAAAAAAAAAAQIAAwQREgUTISIxQVFh/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AM7cnKus/s6mv6LQVwArTIPaOzX5+NNb0zPpCpQW92AIgTZVZVSF+RJsmwPWeJBH8iB5tyOtS3iZ1lF3I+3rxEpyfGAW1S40pgdjGz7qMdk3sb35iUcmxiB2l2utbiBzpax7wbEDqCo/ERAu0WB62GvAMRED/9k=",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-12-640.webp",
        "jpg": "/photos/hero-12-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-12-960.webp",
        "jpg": "/photos/hero-12-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-12-1440.webp",
        "jpg": "/photos/hero-12-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-12-1920.webp",
        "jpg": "/photos/hero-12-1920.jpg"
      }
    ],
    "src": "/photos/hero-12-1920.jpg",
    "srcSet": "/photos/hero-12-640.jpg 640w, /photos/hero-12-960.jpg 960w, /photos/hero-12-1440.jpg 1440w, /photos/hero-12-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-12-640.webp 640w, /photos/hero-12-960.webp 960w, /photos/hero-12-1440.webp 1440w, /photos/hero-12-1920.webp 1920w"
  },
  {
    "name": "hero-13",
    "width": 4000,
    "height": 6000,
    "aspectRatio": 0.6667,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAMFBP/EACQQAAEEAQIGAwAAAAAAAAAAAAEAAgMRBBIxBRMhQVFhIiOB/8QAFQEBAQAAAAAAAAAAAAAAAAAAAQD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCdZyeKTPH4p2XC+OUtdunRZMnO5jKHpaMwjIp9da38qSQQhMe35ISDYKLfarwQ87HZDs49VgwMQ6i+cFrB28p82Y6/qGgbWgl5sEeO/SOp7lCzSOLjbjZQkK+aaicRvdKXvYQhBKQhCQ//2Q==",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-13-640.webp",
        "jpg": "/photos/hero-13-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-13-960.webp",
        "jpg": "/photos/hero-13-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-13-1440.webp",
        "jpg": "/photos/hero-13-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-13-1920.webp",
        "jpg": "/photos/hero-13-1920.jpg"
      }
    ],
    "src": "/photos/hero-13-1920.jpg",
    "srcSet": "/photos/hero-13-640.jpg 640w, /photos/hero-13-960.jpg 960w, /photos/hero-13-1440.jpg 1440w, /photos/hero-13-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-13-640.webp 640w, /photos/hero-13-960.webp 960w, /photos/hero-13-1440.webp 1440w, /photos/hero-13-1920.webp 1920w"
  },
  {
    "name": "hero-14",
    "width": 4000,
    "height": 6000,
    "aspectRatio": 0.6667,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAMEBQL/xAAkEAABAwUAAgEFAAAAAAAAAAABAAIDBAUREiETQTEUIjJSkf/EABUBAQEAAAAAAAAAAAAAAAAAAAEA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8AyZrVPSaTQP5jOU+nujHACV2JPglMbc2VmlO6Nzcej7UNyogT5II9e9CCv8Yne5vy0jIKEukY9lGwnOc4KEFPVymOfzuYAdeYGOpFPc3mTV7dmlV3ioFXL4ombNH6hc0FseSxtRqyPOSSepB0VUGxSGXjc8A9IXVfBT087RFs+E/kB1CCXC8l0gADdW5GAsueqmkeA55/qEJDcsYH05c77iT3bqEIUn//2Q==",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-14-640.webp",
        "jpg": "/photos/hero-14-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-14-960.webp",
        "jpg": "/photos/hero-14-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-14-1440.webp",
        "jpg": "/photos/hero-14-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-14-1920.webp",
        "jpg": "/photos/hero-14-1920.jpg"
      }
    ],
    "src": "/photos/hero-14-1920.jpg",
    "srcSet": "/photos/hero-14-640.jpg 640w, /photos/hero-14-960.jpg 960w, /photos/hero-14-1440.jpg 1440w, /photos/hero-14-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-14-640.webp 640w, /photos/hero-14-960.webp 960w, /photos/hero-14-1440.webp 1440w, /photos/hero-14-1920.webp 1920w"
  },
  {
    "name": "hero-15",
    "width": 3264,
    "height": 4928,
    "aspectRatio": 0.6623,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAUGBAL/xAAjEAACAgIBBAIDAAAAAAAAAAABAgADBBEFBiExQRMiFDJC/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/ANRyOT+Hh2XAbKjtJfA81byFrV3Jo+QRJnUHUK3KaMU7X+ifc99MW1VY1+RvdijxA10TCWc9ljKZ0sIG/EQM2xIY7lbicw0MRV2B/cmcOfStVxKMGVu416nRhBRTtffmBUzUoto+elRsH7RCqtnHuFYAGIGds9zr48bpsiIFbi/tjXIw2uvcRED/2Q==",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-15-640.webp",
        "jpg": "/photos/hero-15-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-15-960.webp",
        "jpg": "/photos/hero-15-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-15-1440.webp",
        "jpg": "/photos/hero-15-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-15-1920.webp",
        "jpg": "/photos/hero-15-1920.jpg"
      }
    ],
    "src": "/photos/hero-15-1920.jpg",
    "srcSet": "/photos/hero-15-640.jpg 640w, /photos/hero-15-960.jpg 960w, /photos/hero-15-1440.jpg 1440w, /photos/hero-15-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-15-640.webp 640w, /photos/hero-15-960.webp 960w, /photos/hero-15-1440.webp 1440w, /photos/hero-15-1920.webp 1920w"
  },
  {
    "name": "hero-16",
    "width": 3415,
    "height": 5123,
    "aspectRatio": 0.6666,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQDBQH/xAAmEAACAgIBAwIHAAAAAAAAAAABAgADBBEhBRIxMlETFCIzQUJh/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAH/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwCunBVPUSRKd10+lBuT9RyWqoaz9R4Ak9DXW4os7grt4EqOgttzn6V8xNMHIsXCDXIDYOOIgcjqVo+XQMNgtyJ419ZoezHsARV5X2MZGnrUf2ZP09fgNzz50JA6BnZB7ks2azyCYlOGdUJWAB2+0QMX+2D+dynuJTn2iIVhSdE6iIgf/9k=",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-16-640.webp",
        "jpg": "/photos/hero-16-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-16-960.webp",
        "jpg": "/photos/hero-16-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-16-1440.webp",
        "jpg": "/photos/hero-16-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-16-1920.webp",
        "jpg": "/photos/hero-16-1920.jpg"
      }
    ],
    "src": "/photos/hero-16-1920.jpg",
    "srcSet": "/photos/hero-16-640.jpg 640w, /photos/hero-16-960.jpg 960w, /photos/hero-16-1440.jpg 1440w, /photos/hero-16-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-16-640.webp 640w, /photos/hero-16-960.webp 960w, /photos/hero-16-1440.webp 1440w, /photos/hero-16-1920.webp 1920w"
  },
  {
    "name": "hero-17",
    "width": 4160,
    "height": 6240,
    "aspectRatio": 0.6667,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGQAAAgMBAAAAAAAAAAAAAAAAAAQCBQYD/8QAIBAAAQQBBQEBAAAAAAAAAAAAAQACAxEEBRIhMUETIv/EABYBAQEBAAAAAAAAAAAAAAAAAAMCAf/EABYRAQEBAAAAAAAAAAAAAAAAAAARAf/aAAwDAQACEQMRAD8AzbGuvnkK20ogZTLNC+koduyw2lPCkbDkse+6BtHVRuB0hLHUMZsTXukABHAQkqWRayhUlUmhjNlxiI47eeikgTIFZ6dLtFGgGoS4jg4o+JbOLeD74hMF5Mhc3tCSj3FVjD8ruwdjxCFCzURQhC1L/9k=",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-17-640.webp",
        "jpg": "/photos/hero-17-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-17-960.webp",
        "jpg": "/photos/hero-17-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-17-1440.webp",
        "jpg": "/photos/hero-17-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-17-1920.webp",
        "jpg": "/photos/hero-17-1920.jpg"
      }
    ],
    "src": "/photos/hero-17-1920.jpg",
    "srcSet": "/photos/hero-17-640.jpg 640w, /photos/hero-17-960.jpg 960w, /photos/hero-17-1440.jpg 1440w, /photos/hero-17-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-17-640.webp 640w, /photos/hero-17-960.webp 960w, /photos/hero-17-1440.webp 1440w, /photos/hero-17-1920.webp 1920w"
  },
  {
    "name": "hero-18",
    "width": 6016,
    "height": 4016,
    "aspectRatio": 1.498,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABgDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAwAE/8QAHxAAAgICAQUAAAAAAAAAAAAAAQIABAMREhMxQWFx/8QAFwEAAwEAAAAAAAAAAAAAAAAAAAECA//EABgRAAMBAQAAAAAAAAAAAAAAAAABAgMh/9oADAMBAAIRAxEAPwBqj0VUtx3uHdWnlZiAw0NTFVyYlIcL9Ec51z7DrwG/Ezd8KUGfHbNdCrAnEO3qUS2a3TOhKC0E4P/Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-18-640.webp",
        "jpg": "/photos/hero-18-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-18-960.webp",
        "jpg": "/photos/hero-18-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-18-1440.webp",
        "jpg": "/photos/hero-18-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-18-1920.webp",
        "jpg": "/photos/hero-18-1920.jpg"
      }
    ],
    "src": "/photos/hero-18-1920.jpg",
    "srcSet": "/photos/hero-18-640.jpg 640w, /photos/hero-18-960.jpg 960w, /photos/hero-18-1440.jpg 1440w, /photos/hero-18-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-18-640.webp 640w, /photos/hero-18-960.webp 960w, /photos/hero-18-1440.webp 1440w, /photos/hero-18-1920.webp 1920w"
  },
  {
    "name": "hero-19",
    "width": 4162,
    "height": 6243,
    "aspectRatio": 0.6667,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGAAAAwEBAAAAAAAAAAAAAAAAAAQFAwb/xAAkEAACAgEEAgIDAQAAAAAAAAABAgADBAURMUESEyFRI0Jhgf/EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDSm+tgVDgnaaYg/H/shplYuHfuULnsb8R+3U6mHsxTsAPlT9wOmosVkCg/IhIOFn22Vm7x/kIHIFixJPJjNFL21OVfbx6+5jRS19oReTK1GkEbhrvFj0IDejZStR6iw8h1CLGmnB5De4ft1CBKJOPexrOxHEd03Kte/Zm33hCBR1UA1Vt3xCEIH//Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-19-640.webp",
        "jpg": "/photos/hero-19-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-19-960.webp",
        "jpg": "/photos/hero-19-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-19-1440.webp",
        "jpg": "/photos/hero-19-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-19-1920.webp",
        "jpg": "/photos/hero-19-1920.jpg"
      }
    ],
    "src": "/photos/hero-19-1920.jpg",
    "srcSet": "/photos/hero-19-640.jpg 640w, /photos/hero-19-960.jpg 960w, /photos/hero-19-1440.jpg 1440w, /photos/hero-19-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-19-640.webp 640w, /photos/hero-19-960.webp 960w, /photos/hero-19-1440.webp 1440w, /photos/hero-19-1920.webp 1920w"
  },
  {
    "name": "hero-20",
    "width": 6720,
    "height": 4480,
    "aspectRatio": 1.5,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAQABgDASIAAhEBAxEB/8QAFwAAAwEAAAAAAAAAAAAAAAAAAAIEA//EACAQAAICAQQDAQAAAAAAAAAAAAECAAMEERITMQUhQWH/xAAVAQEBAAAAAAAAAAAAAAAAAAACAf/EABsRAQACAgMAAAAAAAAAAAAAAAEAAgMREiEx/9oADAMBAAIRAxEAPwDanLRtrA+gYi5F3MzbhxnrWFVbIpAAP5K6VIpCPWrAdQVvp7ldJJE8grFgwJ0+iERMOypnIA0Y9QicyeQcSf/Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-20-640.webp",
        "jpg": "/photos/hero-20-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-20-960.webp",
        "jpg": "/photos/hero-20-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-20-1440.webp",
        "jpg": "/photos/hero-20-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-20-1920.webp",
        "jpg": "/photos/hero-20-1920.jpg"
      }
    ],
    "src": "/photos/hero-20-1920.jpg",
    "srcSet": "/photos/hero-20-640.jpg 640w, /photos/hero-20-960.jpg 960w, /photos/hero-20-1440.jpg 1440w, /photos/hero-20-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-20-640.webp 640w, /photos/hero-20-960.webp 960w, /photos/hero-20-1440.webp 1440w, /photos/hero-20-1920.webp 1920w"
  },
  {
    "name": "hero-21",
    "width": 3840,
    "height": 2160,
    "aspectRatio": 1.7778,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAOABgDASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAAAAMEBf/EAB8QAAICAQUBAQAAAAAAAAAAAAECAAQDERIhQVETMf/EABYBAQEBAAAAAAAAAAAAAAAAAAMAAf/EABgRAAMBAQAAAAAAAAAAAAAAAAABAhEh/9oADAMBAAIRAxEAPwBgyMCNToJe5azhNcb7QB+iBVHzPPPs5T2Wyu1YcBO/YcznSdGytZL49+UksDEhVLOrKSNo6iFaWmqmf//Z",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-21-640.webp",
        "jpg": "/photos/hero-21-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-21-960.webp",
        "jpg": "/photos/hero-21-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-21-1440.webp",
        "jpg": "/photos/hero-21-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-21-1920.webp",
        "jpg": "/photos/hero-21-1920.jpg"
      }
    ],
    "src": "/photos/hero-21-1920.jpg",
    "srcSet": "/photos/hero-21-640.jpg 640w, /photos/hero-21-960.jpg 960w, /photos/hero-21-1440.jpg 1440w, /photos/hero-21-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-21-640.webp 640w, /photos/hero-21-960.webp 960w, /photos/hero-21-1440.webp 1440w, /photos/hero-21-1920.webp 1920w"
  },
  {
    "name": "hero-22",
    "width": 3510,
    "height": 5265,
    "aspectRatio": 0.6667,
    "lqip": "data:image/jpeg;base64,/9j/2wBDABQODxIPDRQSEBIXFRQYHjIhHhwcHj0sLiQySUBMS0dARkVQWnNiUFVtVkVGZIhlbXd7gYKBTmCNl4x9lnN+gXz/2wBDARUXFx4aHjshITt8U0ZTfHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHx8fHz/wAARCAAkABgDASIAAhEBAxEB/8QAGAABAQEBAQAAAAAAAAAAAAAAAAQCAwX/xAAiEAABBAICAwADAAAAAAAAAAABAAIDEQQSEyEFMUEUMmH/xAAXAQEBAQEAAAAAAAAAAAAAAAACAwEA/8QAGREBAAMBAQAAAAAAAAAAAAAAAAECMREh/9oADAMBAAIRAxEAPwD3Q6yH+lp1PBJ7CxBxZEBYOhVKLPc/D4oonnW0eTYcSZzC5xHz4i75UR6J+iwiLWvG5AY47nVv9XHzGQ2XXid+pu1DDkNlpjrBW8nHflR1FQ1PatXyAtPVrZfyIY5Ab6qkUkG+Fj8TiCfaKU6UZ6khA5NvoVbnGMN1Nbe0RUjASZjnbeyiIsc//9k=",
    "variants": [
      {
        "width": 640,
        "webp": "/photos/hero-22-640.webp",
        "jpg": "/photos/hero-22-640.jpg"
      },
      {
        "width": 960,
        "webp": "/photos/hero-22-960.webp",
        "jpg": "/photos/hero-22-960.jpg"
      },
      {
        "width": 1440,
        "webp": "/photos/hero-22-1440.webp",
        "jpg": "/photos/hero-22-1440.jpg"
      },
      {
        "width": 1920,
        "webp": "/photos/hero-22-1920.webp",
        "jpg": "/photos/hero-22-1920.jpg"
      }
    ],
    "src": "/photos/hero-22-1920.jpg",
    "srcSet": "/photos/hero-22-640.jpg 640w, /photos/hero-22-960.jpg 960w, /photos/hero-22-1440.jpg 1440w, /photos/hero-22-1920.jpg 1920w",
    "webpSrcSet": "/photos/hero-22-640.webp 640w, /photos/hero-22-960.webp 960w, /photos/hero-22-1440.webp 1440w, /photos/hero-22-1920.webp 1920w"
  }
];

export const photosByName: Record<string, Photo> = Object.fromEntries(
  photos.map((p) => [p.name, p]),
);
