// Static seed content for the group games engine (server/group-games.ts).
// Plain arrays, single source of truth per kind — same convention as
// EVENT_KINDS/GENDER_OPTIONS elsewhere in this codebase. No admin UI yet;
// expand these arrays directly to add variety.

export const WOULD_YOU_RATHER_BANK: { a: string; b: string }[] = [
  { a: "Always be 10 minutes late", b: "Always be 20 minutes early" },
  { a: "Have unlimited data but slow internet", b: "Blazing internet with a strict data cap" },
  { a: "Give up your phone for a month", b: "Give up your car/transport app for a month" },
  { a: "Always know when someone's lying to you", b: "Always get away with any lie you tell" },
  { a: "Be famous for something embarrassing", b: "Be completely unknown forever" },
  { a: "Live without music", b: "Live without movies/TV" },
  { a: "Have a rewind button on life", b: "Have a pause button on life" },
  { a: "Only eat your favorite meal forever", b: "Never eat that meal again" },
  { a: "Read minds", b: "See 10 minutes into the future" },
  { a: "Always have to whisper", b: "Always have to shout" },
  { a: "Lose your sense of smell", b: "Lose your sense of taste" },
  { a: "Be the funniest person in the room", b: "Be the smartest person in the room" },
  { a: "Travel to the past", b: "Travel to the future" },
  { a: "Never use social media again", b: "Never watch another movie or show again" },
  { a: "Have a personal chef", b: "Have a personal driver" },
  { a: "Always overdress for events", b: "Always underdress for events" },
  { a: "Win a small amount of money every week for life", b: "Win one huge amount once" },
  { a: "Be unable to lie", b: "Be unable to keep a secret" },
  { a: "Live in a city apartment", b: "Live on a farm out of town" },
  { a: "Have everyone know your search history", b: "Have everyone hear your inner thoughts" },
];

export const THIS_OR_THAT_BANK: { a: string; b: string }[] = [
  { a: "Beach", b: "Mountains" },
  { a: "Sadza", b: "Rice" },
  { a: "Morning person", b: "Night owl" },
  { a: "Sweet", b: "Savory" },
  { a: "Big wedding", b: "Small wedding" },
  { a: "Text", b: "Call" },
  { a: "City life", b: "Rural life" },
  { a: "Braai", b: "Restaurant" },
  { a: "Window seat", b: "Aisle seat" },
  { a: "Coffee", b: "Tea" },
  { a: "Dogs", b: "Cats" },
  { a: "Netflix", b: "Cinema" },
  { a: "Planner", b: "Spontaneous" },
  { a: "Sneakers", b: "Formal shoes" },
  { a: "Load-shedding at night", b: "Load-shedding in the day" },
  { a: "Save it", b: "Spend it" },
  { a: "Amapiano", b: "Old school" },
  { a: "Early wedding RSVP", b: "Decide on the day" },
  { a: "Long walk", b: "Gym session" },
  { a: "Group chat", b: "One-on-one" },
];

export const NEVER_HAVE_I_EVER_BANK: string[] = [
  "Never have I ever ghosted someone",
  "Never have I ever stalked an ex's social media",
  "Never have I ever lied about my age",
  "Never have I ever shown up to the wrong venue",
  "Never have I ever pretended to like a gift",
  "Never have I ever fallen asleep during a date",
  "Never have I ever double-booked two dates in one night",
  "Never have I ever used a fake name on a first date",
  "Never have I ever cried during a movie in public",
  "Never have I ever sent a text to the wrong person",
  "Never have I ever left a party without saying bye",
  "Never have I ever pretended to be busy to avoid plans",
  "Never have I ever eaten food that fell on the floor",
  "Never have I ever laughed at the wrong moment",
  "Never have I ever forgotten someone's name right after meeting them",
  "Never have I ever gone on a date just for the free meal",
  "Never have I ever stayed friends with an ex",
  "Never have I ever pretended to know a song I'd never heard",
  "Never have I ever shown up somewhere in the wrong outfit",
  "Never have I ever ignored a call I knew who was calling",
];

export const MOST_LIKELY_TO_BANK: string[] = [
  "Most likely to remember everyone's birthday",
  "Most likely to plan the group's next trip",
  "Most likely to make everyone laugh first",
  "Most likely to be the last one still dancing",
  "Most likely to give the best advice",
  "Most likely to try any new restaurant in town",
  "Most likely to be everyone's emergency contact",
  "Most likely to start a business one day",
  "Most likely to know a great playlist for any mood",
  "Most likely to organize a surprise party",
  "Most likely to talk their way out of anything",
  "Most likely to be the calm one in a crisis",
  "Most likely to become a regular somewhere new instantly",
  "Most likely to give the best gifts",
  "Most likely to know a shortcut for everything",
];

export const TRIVIA_BANK: { question: string; options: [string, string, string, string]; correctIndex: 0 | 1 | 2 | 3 }[] = [
  { question: "What's the capital of Zimbabwe?", options: ["Bulawayo", "Harare", "Mutare", "Gweru"], correctIndex: 1 },
  { question: "How many players are on a football pitch per team?", options: ["9", "10", "11", "12"], correctIndex: 2 },
  { question: "What's the largest ocean on Earth?", options: ["Atlantic", "Indian", "Arctic", "Pacific"], correctIndex: 3 },
  { question: "Which planet is known as the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Saturn"], correctIndex: 1 },
  { question: "How many strings does a standard guitar have?", options: ["4", "5", "6", "7"], correctIndex: 2 },
  { question: "What's the smallest country in the world?", options: ["Monaco", "Malta", "Vatican City", "Liechtenstein"], correctIndex: 2 },
  { question: "Which continent is Zimbabwe on?", options: ["Asia", "Africa", "South America", "Europe"], correctIndex: 1 },
  { question: "What gas do plants absorb from the air?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correctIndex: 2 },
  { question: "How many continents are there?", options: ["5", "6", "7", "8"], correctIndex: 2 },
  { question: "What's the currency mostly used in Zimbabwe today?", options: ["Zimbabwe Dollar only", "USD", "Rand only", "Euro"], correctIndex: 1 },
  { question: "Which animal is the fastest on land?", options: ["Lion", "Cheetah", "Horse", "Leopard"], correctIndex: 1 },
  { question: "How many bones are in the adult human body?", options: ["186", "206", "226", "246"], correctIndex: 1 },
  { question: "What's the longest river in Africa?", options: ["Congo", "Zambezi", "Nile", "Limpopo"], correctIndex: 2 },
  { question: "Which sport uses a shuttlecock?", options: ["Tennis", "Squash", "Badminton", "Table tennis"], correctIndex: 2 },
  { question: "What's the freezing point of water in Celsius?", options: ["0", "10", "32", "-1"], correctIndex: 0 },
  { question: "Which famous falls are on the Zambezi River?", options: ["Niagara Falls", "Victoria Falls", "Angel Falls", "Iguazu Falls"], correctIndex: 1 },
  { question: "How many days are in a leap year?", options: ["364", "365", "366", "367"], correctIndex: 2 },
  { question: "What's the main language spoken across most of Zimbabwe?", options: ["Zulu", "Shona", "Swahili", "Xhosa"], correctIndex: 1 },
  { question: "Which instrument has 88 keys?", options: ["Organ", "Piano", "Accordion", "Xylophone"], correctIndex: 1 },
  { question: "What do bees collect from flowers?", options: ["Pollen", "Nectar", "Both", "Neither"], correctIndex: 2 },
];

export const CATEGORY_SPRINT_BANK: string[] = [
  "Things found at a wedding",
  "Things you'd take on a road trip",
  "Things that are red",
  "Things found in a kitchen",
  "Fast food chains",
  "Things you do before bed",
  "Things found at a braai",
  "Songs you know all the words to",
  "Things that make a good first date",
  "Things found in a school bag",
  "Words that rhyme with 'love'",
  "Things you'd bring to a picnic",
  "Zimbabwean foods",
  "Things that are surprisingly heavy",
  "Reasons to cancel plans last minute",
];

export const EMOJI_CHARADES_BANK: { answer: string; emoji: string }[] = [
  { answer: "The Lion King", emoji: "🦁👑🌍" },
  { answer: "Titanic", emoji: "🚢🧊💔" },
  { answer: "Spider-Man", emoji: "🕷️🧑‍🦱🏙️" },
  { answer: "Frozen", emoji: "❄️👸⛄" },
  { answer: "Black Panther", emoji: "🐆👑🇿🇦" },
  { answer: "Finding Nemo", emoji: "🐠🔍🌊" },
  { answer: "Home Alone", emoji: "🏠🙅‍♂️🎄" },
  { answer: "Fast and Furious", emoji: "🏎️💨😤" },
  { answer: "The Notebook", emoji: "📓❤️🌧️" },
  { answer: "Toy Story", emoji: "🤠🚀🧸" },
  { answer: "Jurassic Park", emoji: "🦖🏝️🚙" },
  { answer: "Shrek", emoji: "🟢👹🧅" },
  { answer: "Avatar", emoji: "🔵🌳🪶" },
  { answer: "Money Heist", emoji: "💰🎭🏦" },
  { answer: "Game of Thrones", emoji: "🐉👑⚔️" },
];

export const ICEBREAKER_BANK: string[] = [
  "What's a weird food combo you swear by?",
  "What's the last show you binge-watched?",
  "What's your go-to karaoke song?",
  "What's a skill you wish you had?",
  "What's the best meal you've had this year?",
  "What's a hot take you stand by?",
  "What's your comfort movie?",
  "What's the most spontaneous thing you've done?",
  "What's a place you want to visit before you're 40?",
  "What song instantly puts you in a good mood?",
  "What's your love language, honestly?",
  "What's a small thing that makes your day better?",
  "What's the last thing you laughed really hard at?",
  "What's a food you refuse to eat?",
  "If you could have dinner with anyone, who would it be?",
  "What's your ideal Sunday?",
  "What app do you spend the most time on?",
  "What's a childhood memory that still makes you smile?",
  "What's your go-to order at a restaurant you've never been to?",
  "What's one thing on your bucket list?",
];
