// Regenerates the responsive variants for the Landing photo slots, and the
// hero rotation manifest client/src/lib/photos.ts (the actual thing Landing
// reads at runtime — the variant files alone aren't enough, see below).
// Source originals live in client/public/photos/_src/<slot>.jpg (git-ignored);
//
//   npm run photos
//
// Two slot shapes, two output shapes:
//   - Named slots (hero-primary, hero-secondary, turn, closing, group-*):
//     4 webp variants + ONE plain <slot>.jpg (1440w) — Landing.tsx's local
//     photo() helper builds a URL straight from the slot name for these,
//     no manifest entry.
//   - Numbered hero-N (the rotating set): 4 webp variants AND 4 width-
//     suffixed jpg variants (hero-N-640.jpg … hero-N-1920.jpg) — every
//     hero-N-*.jpg referenced by the photos.ts manifest below has to
//     actually exist on disk, and older hero-N slots (whose _src originals
//     are long gone, cleaned up as git-ignored files tend to be) already
//     have exactly this shape sitting in client/public/photos/ from
//     whenever they were first generated — matching it here keeps every
//     hero-N slot on the same real file set instead of two different ones.
import sharp from "sharp";
import { readdir, mkdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const photosDir = join(dirname(fileURLToPath(import.meta.url)), "..", "client", "public", "photos");
const srcDir = join(photosDir, "_src");
const manifestPath = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "client",
  "src",
  "lib",
  "photos.ts",
);

const WIDTHS = [640, 960, 1440, 1920];

// slot -> [w, h] aspect ratio the frame reserves
const RATIOS = {
  "hero-primary": [4, 5],
  "hero-secondary": [1, 1],
  "turn": [16, 9],
  "group-late-practice": [3, 2],
  "group-sunday-trail": [3, 2],
  "group-table-for-six": [3, 2],
  "closing": [16, 9],
};

// hero-1 … hero-N — the rotating hero set, all cropped to the 4:5 hero frame
const isHeroSlot = (slot) => /^hero-\d+$/.test(slot);
const heroRatio = (slot) => (isHeroSlot(slot) ? [4, 5] : undefined);

const files = (await readdir(srcDir)).filter((f) => /\.(jpe?g|png)$/i.test(f));
await mkdir(photosDir, { recursive: true });

for (const file of files) {
  const slot = file.replace(/\.(jpe?g|png)$/i, "");
  const ratio = RATIOS[slot] ?? heroRatio(slot);
  if (!ratio) {
    console.warn(`  ${slot}: no ratio mapping, skipped`);
    continue;
  }
  const [rw, rh] = ratio;
  const input = join(srcDir, file);
  const hero = isHeroSlot(slot);

  for (const w of WIDTHS) {
    const h = Math.round((w * rh) / rw);
    await sharp(input)
      .resize(w, h, { fit: "cover", position: "centre" })
      .webp({ quality: 78 })
      .toFile(join(photosDir, `${slot}-${w}.webp`));
    if (hero) {
      await sharp(input)
        .resize(w, h, { fit: "cover", position: "centre" })
        .jpeg({ quality: 80, mozjpeg: true })
        .toFile(join(photosDir, `${slot}-${w}.jpg`));
    }
  }
  if (!hero) {
    // Named slots only — photo() in Landing.tsx expects one plain
    // <slot>.jpg, no width suffix.
    const h1440 = Math.round((1440 * rh) / rw);
    await sharp(input)
      .resize(1440, h1440, { fit: "cover", position: "centre" })
      .jpeg({ quality: 80, mozjpeg: true })
      .toFile(join(photosDir, `${slot}.jpg`));
  }

  console.log(`  ${slot.padEnd(22)} ${rw}:${rh}  -> 4 webp${hero ? " + 4 jpg" : " + jpg"}`);
}

// --- rebuild client/src/lib/photos.ts, the hero-N rotation manifest ---
//
// This is the piece Landing.tsx (RotatingPhoto / HERO_SET) actually reads at
// runtime — the image files above aren't enough on their own. It used to
// claim to be generated by a script/photos.ts that doesn't exist in this
// repo, so it silently stopped tracking new hero-N slots; folded the job in
// here instead so `npm run photos` does the whole thing every time.
//
// hero-N's _src originals aren't guaranteed to still be on disk (git-ignored,
// and older ones have been cleaned up before) — read dimensions/LQIP from
// each slot's own generated hero-N-1920.jpg output instead of _src, so this
// works uniformly whether or not the source is still around. width/height/
// aspectRatio here are informational only (Landing.tsx hardcodes its own
// 4:5 frame ratio and never reads these three fields) — lqip is the one
// field that's actually rendered (blur-up placeholder background).
const heroFiles = (await readdir(photosDir))
  .filter((f) => /^hero-\d+-1920\.jpg$/.test(f))
  .map((f) => ({ name: f.replace(/-1920\.jpg$/, ""), n: Number(f.match(/\d+/)[0]) }))
  .sort((a, b) => a.n - b.n);

const photoEntries = [];
for (const { name } of heroFiles) {
  const file = join(photosDir, `${name}-1920.jpg`);
  const meta = await sharp(file).metadata();
  const width = meta.width;
  const height = meta.height;
  const aspectRatio = Math.round((width / height) * 10000) / 10000;
  const lqipBuffer = await sharp(file)
    .resize(24)
    .jpeg({ quality: 40 })
    .toBuffer();
  const lqip = `data:image/jpeg;base64,${lqipBuffer.toString("base64")}`;
  const variants = WIDTHS.map((w) => ({
    width: w,
    webp: `/photos/${name}-${w}.webp`,
    jpg: `/photos/${name}-${w}.jpg`,
  }));
  photoEntries.push({
    name,
    width,
    height,
    aspectRatio,
    lqip,
    variants,
    src: `/photos/${name}-1920.jpg`,
    srcSet: variants.map((v) => `${v.jpg} ${v.width}w`).join(", "),
    webpSrcSet: variants.map((v) => `${v.webp} ${v.width}w`).join(", "),
  });
}

const manifestSource = `// AUTO-GENERATED by scripts/resize-photos.mjs — do not edit by hand.
// Run \`npm run photos\` to regenerate after changing client/public/photos/_src/.

export interface PhotoVariant {
  width: number;
  webp: string;
  jpg: string;
}

export interface Photo {
  /** Base name without extension, e.g. "hero-1". */
  name: string;
  /** Intrinsic (EXIF-oriented) pixel dimensions of the source. */
  width: number;
  height: number;
  /** width / height, rounded to 4 dp. */
  aspectRatio: number;
  /** Tiny blurred JPG as a data URI, for blur-up placeholders. */
  lqip: string;
  /** Emitted sizes, ascending by width. */
  variants: PhotoVariant[];
  /** Largest JPG URL — use as a plain <img src> fallback. */
  src: string;
  /** JPG srcset string for <img srcset> / <source>. */
  srcSet: string;
  /** WebP srcset string for a <source type="image/webp">. */
  webpSrcSet: string;
}

export const photos: Photo[] = ${JSON.stringify(photoEntries, null, 2)};

export const photosByName: Record<string, Photo> = Object.fromEntries(
  photos.map((p) => [p.name, p]),
);
`;

await writeFile(manifestPath, manifestSource);
console.log(`  photos.ts manifest: ${photoEntries.length} hero-N entries`);

console.log("photos regenerated.");
